# Generated by Django 3.2.15 on 2022-08-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('NEWS', 'news'), ('ARTICAL', 'Artical'), ('BLOG', 'Blog'), ('FAQ', 'Faq'), ('LEGAL TERMS', 'Legal Terms')], max_length=300)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
