# Generated by Django 3.2.15 on 2022-08-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0005_alter_category_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.CharField(choices=[('Yes', True), ('No', False)], max_length=300),
        ),
    ]
