# Generated by Django 3.2.15 on 2022-08-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0006_alter_category_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], max_length=300),
        ),
    ]
