# Generated by Django 3.2.15 on 2022-09-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0007_alter_category_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=300, null=True)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keyword', models.CharField(max_length=300)),
                ('og_title', models.TextField(blank=True)),
                ('og_description', models.CharField(max_length=300)),
                ('og_url', models.CharField(max_length=150)),
                ('canonical_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': '_blog',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=300, null=True)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keyword', models.CharField(max_length=300)),
                ('og_title', models.TextField(blank=True)),
                ('og_description', models.CharField(max_length=300)),
                ('og_url', models.CharField(max_length=150)),
                ('canonical_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': '_faq',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='media/')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], max_length=300, null=True)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keyword', models.CharField(max_length=300)),
                ('og_title', models.TextField(blank=True)),
                ('og_description', models.CharField(max_length=300)),
                ('og_url', models.CharField(max_length=150)),
                ('canonical_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': '_news',
            },
        ),
    ]
