# Generated by Django 3.2.15 on 2022-09-14 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_management', '0009_auto_20220914_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
    ]
